if-shell '[ -x /opt/homebrew/opt/bash/bin/bash ] && ! printf %s ":$PATH:" | grep -Fq ":/opt/homebrew/opt/bash/bin:"' 'set-environment -gF PATH "/opt/homebrew/opt/bash/bin:#{PATH}"'
if-shell '[ ! -x /opt/homebrew/opt/bash/bin/bash ] && [ -x /usr/local/opt/bash/bin/bash ] && ! printf %s ":$PATH:" | grep -Fq ":/usr/local/opt/bash/bin:"' 'set-environment -gF PATH "/usr/local/opt/bash/bin:#{PATH}"'
set -g @gruvbox-tmux_theme dark
set -g @gruvbox-tmux_github_status on
