# Set reload binding
unbind r
bind r source-file ~/.tmux.conf

# Set leader keymap
unbind s
set -g prefix C-s

# Plugin installation
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'omerxx/tmux-floax'
set -g @plugin 'adibhanna/gruvbox-tmux'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'TanglingTreats/tmux-everforest'

# Plugin configuration
set -g @sessionx-bind 's'

set -g @floax-change-path 'false'
set -g @floax-session-name 'floax'

# Configure dark and light theme support
if -F '#{==:#{client_theme},dark}' {
  set -g @tmux-everforest 'dark-medium'
} {
  set -g @tmux-everforest 'light-medium'
}

# Enable mouse control
set -g mouse on

# Set navigation bindings
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Set new panes to follow current path
bind  c  new-window      -c "#{pane_current_path}"
bind  %  split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

# Global settings
set -g base-index 1
set-option -g status-position top
set -g mode-keys vi
set -g extended-keys on
set -g extended-keys-format csi-u

# 24-bit colors end-to-end
set -g default-terminal "tmux-256color"
set -as terminal-features "tmux-256color:RGB,alacritty:RGB,xterm-256color:RGB"

# keep COLORTERM for apps like btop
set -ga update-environment ",COLORTERM"

# Initialize TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'

