# Set reload binding
unbind r
bind r source-file ~/.tmux.conf

# Set leader keymap
set -g prefix C-s

# Enable mouse control
set -g mouse on

# Set navigation bindings
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
source-file -q ~/.config/omarchy/current/theme/tmux.conf

# Start window and pane numbering at 1
set -g base-index 1

# Set the status position to top
set-option -g status-position top

# Use vi key-mode for selection
set -g mode-keys vi

# Add FloaX for floating panes
set -g @plugin 'omerxx/tmux-floax'

# Initialize TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'

# 24-bit colors end-to-end
set -g default-terminal "tmux-256color"
set -as terminal-features "tmux-256color:RGB,alacritty:RGB,xterm-256color:RGB"

# keep COLORTERM for apps like btop
set -ga update-environment ",COLORTERM"

